# Use official Python image as the base
FROM python:3.12

# Set working directory
WORKDIR /app

# Copy the project files to the container
COPY . /app

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose FastAPI port
EXPOSE 8000

ENV CUDA_VISIBLE_DEVICES=""

# Run both MLflow server and FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]