name: myenv
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.12
  - pip
  - zstd=1.5.6
  - zlib=1.3.1
  - zstandard
  - numpy
  - tensorflow=2.17.0
  - pytorch=2.4.1
  - sentence-transformers
  - fastapi
  - uvicorn
  - pip:
      - requests