# my_ml_project/Dockerfile

# Use official Python image as the base
FROM ghcr.io/mlflow/mlflow:v2.17.2

# Install Python dependencies
COPY mlflow_requirements.txt requirements.txt

RUN pip install -r requirements.txt

