# my_ml_project/Dockerfile

# Use official Python image as the base
FROM apache/airflow:latest

# Install Python dependencies
COPY airflow_requirements.txt /opt/airflow/requirements.txt

RUN pip install -r requirements.txt

